title: Neha Mandhare
logo: /assets/img/mypic.png
description: I am a versatile, hard-working, and creative individual and always find ways to broaden my knowledge. In spite of being a chemical engineer, I have good knowledge of Python, data visualization, R, Power BI, Machine learning, and Tableau. I have hands-on experience on projects which I have completed from Simplilearn while completing my Data scientist course.
show_ downloads: true
theme: jekyll-theme-minimal
